# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Relic_config = debug
  BasicRelicApp_config = debug
  PlayableRelicApp_config = debug
endif
ifeq ($(config),release)
  Relic_config = release
  BasicRelicApp_config = release
  PlayableRelicApp_config = release
endif
ifeq ($(config),dist)
  Relic_config = dist
  BasicRelicApp_config = dist
  PlayableRelicApp_config = dist
endif

PROJECTS := Relic BasicRelicApp PlayableRelicApp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Relic:
ifneq (,$(Relic_config))
	@echo "==== Building Relic ($(Relic_config)) ===="
	@${MAKE} --no-print-directory -C Relic -f Makefile config=$(Relic_config)
endif

BasicRelicApp: Relic
ifneq (,$(BasicRelicApp_config))
	@echo "==== Building BasicRelicApp ($(BasicRelicApp_config)) ===="
	@${MAKE} --no-print-directory -C Examples/BasicRelicApp -f Makefile config=$(BasicRelicApp_config)
endif

PlayableRelicApp: Relic
ifneq (,$(PlayableRelicApp_config))
	@echo "==== Building PlayableRelicApp ($(PlayableRelicApp_config)) ===="
	@${MAKE} --no-print-directory -C Examples/PlayableRelicApp -f Makefile config=$(PlayableRelicApp_config)
endif

clean:
	@${MAKE} --no-print-directory -C Relic -f Makefile clean
	@${MAKE} --no-print-directory -C Examples/BasicRelicApp -f Makefile clean
	@${MAKE} --no-print-directory -C Examples/PlayableRelicApp -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Relic"
	@echo "   BasicRelicApp"
	@echo "   PlayableRelicApp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"