# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Relic_config = debug
  RelicApp_config = debug
endif
ifeq ($(config),release)
  Relic_config = release
  RelicApp_config = release
endif
ifeq ($(config),dist)
  Relic_config = dist
  RelicApp_config = dist
endif

PROJECTS := Relic RelicApp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Relic:
ifneq (,$(Relic_config))
	@echo "==== Building Relic ($(Relic_config)) ===="
	@${MAKE} --no-print-directory -C Relic -f Makefile config=$(Relic_config)
endif

RelicApp: Relic
ifneq (,$(RelicApp_config))
	@echo "==== Building RelicApp ($(RelicApp_config)) ===="
	@${MAKE} --no-print-directory -C RelicApp -f Makefile config=$(RelicApp_config)
endif

clean:
	@${MAKE} --no-print-directory -C Relic -f Makefile clean
	@${MAKE} --no-print-directory -C RelicApp -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Relic"
	@echo "   RelicApp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"